version: '3'

volumes:
    local_postgres_data: {}
    local_postgres_data_backups: {}

services:
    postgres:
        image: postgres:11
        volumes:
            - local_postgres_data:/var/lib/postgresql/data
            - local_postgres_data_backups:/backups
        ports:
            - "5430:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: api

    django: &django
        build: 
            context: ./api            
        command: python manage.py runserver 0.0.0.0:8000
        image: api_crm_sales
        depends_on:
            - postgres
        volumes:
            - .:/code
        ports:
            - "8000:8000"
