# Generated by Django 3.1.4 on 2020-12-23 06:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_memebership',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesmodule',
            name='initial_amount_cash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesmodule',
            name='is_sales_box',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='date_time_done',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipping',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='typepayment',
            name='is_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='typepayment',
            name='is_cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='typepayment',
            name='is_credit_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='typepayment',
            name='is_debit_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='client',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='config',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_order', to='crm.order'),
        ),
        migrations.AlterField(
            model_name='price',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='salesmodule',
            name='initial_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesmodule',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='typepayment',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified', verbose_name='modified at'),
        ),
    ]
