# Generated by Django 3.1.4 on 2020-12-25 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20201223_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_order', to='crm.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sales_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_module_payment', to='crm.salesmodule'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_payment', to='crm.typepayment'),
        ),
        migrations.AlterField(
            model_name='salesmodule',
            name='initial_amount_cash',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesmodule',
            name='is_sales_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='address',
            field=models.TextField(blank=True, max_length='200', null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='date_time_done',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
