# Generated by Django 3.1.4 on 2020-12-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20201225_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='is_cancelled',
        ),
    ]
